version: "3.9"

services:
  backend:
    image: start:latest
    networks:
      - network_public
    environment:
      NODE_ENV: production
      PORT: 3007
      OAUTH_SERVER_URL: "https://portal.iecg.com.br"
      VITE_API_URL: "https://portal.iecg.com.br"
    command: >
      sh -c "
      cd /app;
      if [ ! -d .git ]; then
        echo '📥 Clonando repositório...';
        rm -rf /app/*;
        git clone https://github.com/queziajesuinod/start-iecg-form.git .;
      else
        echo '📢 Atualizando código...';
        git restore --staged .env 2>/dev/null || true;
        git update-index --assume-unchanged .env 2>/dev/null || true;
        git fetch --all && git reset --hard origin/main || true;
        git pull 

      fi &&
      pnpm install  &&
      pnpm build &&
      pnpm start
      "
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3
      labels:
        # Habilitar Traefik
        - "traefik.enable=true"
        - "traefik.docker.network=network_public"
        
        # Router HTTPS
        - "traefik.http.routers.startiecg-secure.rule=Host(`start.iecg.com.br` )"
        - "traefik.http.routers.startiecg-secure.entrypoints=websecure"
        - "traefik.http.routers.startiecg-secure.tls=true"
        - "traefik.http.routers.startiecg-secure.tls.certresolver=letsencryptresolver"
        
        # Router HTTP (redirect )
        - "traefik.http.routers.startiecg.rule=Host(`start.iecg.com.br` )"
        - "traefik.http.routers.startiecg.entrypoints=web"
        - "traefik.http.routers.startiecg.middlewares=https-redirect"
        
        # Service (porta do container )
        - "traefik.http.services.startiecg-service.loadbalancer.server.port=3007"
        
        # Middleware redirect HTTPS
        - "traefik.http.middlewares.https-redirect.redirectscheme.scheme=https"
        - "traefik.http.middlewares.https-redirect.redirectscheme.permanent=true"

networks:
  network_public:
    external: true
