export const CAMPUS_NAMES = [
  "CAMPUS IECG CENTRO",
  "CAMPUS IECG AERO RANCHO",
  "CAMPUS IECG ARARAQUARA",
  "CAMPUS IECG BANDEIRANTES",
  "CAMPUS IECG DOURADOS",
  "CAMPUS IECG LOS ANGELES",
  "CAMPUS IECG MARGARIDA",
  "CAMPUS IECG PALHOÇA",
  "CAMPUS IECG PONTA PORÃ",
  "CAMPUS IECG RIBAS DO RIO PARDO",
  "CAMPUS IECG VILA VELHA",
  "CAMPUS GUARUJÁ"
];
